FROM manimcommunity/manim:stable

WORKDIR /app

COPY . .

RUN pip install fastapi uvicorn gunicorn python-multipart

EXPOSE 10000

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10000"]