FROM manimcommunity/manim:stable

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    gunicorn \
    pydantic \
    numpy \
    matplotlib \
    pandas \
    python-multipart

COPY . .

EXPOSE 10000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:10000"]